export enum ActionTypes {
    ANSWER_QUESTION = "ANSWER_QUESTION",
    END_GAME = "END_GAME",
    FETCH_QUESTIONS = "LOAD_QUESTIONS",
    LOG_ANSWER = "LOG_ANSWER",
    NEXT_QUESTION = "NEXT_QUESTION",
    SET_QUESTIONS = "SET_QUESTIONS",
    START_GAME = "START_GAME"
}
